/**
 * Frond outline (silhouette) — how pinnae length/width changes along the rachis.
 * Used in the identifier UI, database search, and identification wizard (after sori type).
 */
export type FrondOutlineId =
  | 'very-narrow'
  | 'narrow'
  | 'broad'
  | 'triangle'
  | 'multi-triangle';

export const FROND_OUTLINE_DEFINITIONS: Record<
  FrondOutlineId,
  { name: string; description: string }
> = {
  'very-narrow': {
    name: 'Very narrow',
    description: 'Parallel sides; may taper down to the rachis.',
  },
  narrow: {
    name: 'Narrow',
    description:
      'Lowest pinna much shorter than mid; broadest at mid; may taper down to the rachis.',
  },
  broad: {
    name: 'Broad',
    description: 'Lowest pinna much wider than mid; obviously broader in the lower–mid frond.',
  },
  triangle: {
    name: 'Triangle',
    description: 'Lowest pinna widest; classic triangular frond outline.',
  },
  'multi-triangle': {
    name: '3+ triangles',
    description: 'Frond appears to have three or more triangular sections.',
  },
};

/** Display order in the identifier frond-outline step. */
export const FROND_OUTLINE_ORDER: FrondOutlineId[] = [
  'very-narrow',
  'narrow',
  'broad',
  'triangle',
  'multi-triangle',
];

export const FROND_OUTLINE_BY_SCIENTIFIC: Record<string, FrondOutlineId> = {
  'Polystichum acrostichoides': 'narrow',
  'Athyrium filix-femina': 'narrow',
  'Osmundastrum cinnamomeum': 'narrow',
  'Adiantum pedatum': 'multi-triangle',
  'Pteridium aquilinum': 'triangle',
  'Dennstaedtia punctilobula': 'triangle',
  'Matteuccia struthiopteris': 'narrow',
  'Asplenium rhizophyllum': 'very-narrow',
  'Polystichum munitum': 'narrow',
  'Polystichum braunii': 'narrow',
  'Polystichum andersonii': 'narrow',
  'Polystichum kruckebergii': 'narrow',
  'Polystichum imbricans': 'narrow',
  'Onoclea sensibilis': 'triangle',
  'Osmunda regalis': 'narrow',
  'Osmunda claytoniana': 'triangle',
  'Thelypteris noveboracensis': 'narrow',
  'Woodwardia areolata': 'broad',
  'Dryopteris marginalis': 'narrow',
  'Thelypteris palustris': 'narrow',
  'Asplenium platyneuron': 'very-narrow',
  'Asplenium trichomanes': 'very-narrow',
  'Polypodium virginianum': 'narrow',
  'Dryopteris carthusiana': 'narrow',
  'Dryopteris intermedia': 'narrow',
  'Phegopteris connectilis': 'triangle',
  'Phegopteris hexagonoptera': 'broad',
  'Gymnocarpium dryopteris': 'triangle',
  'Cystopteris bulbifera': 'very-narrow',
  'Cystopteris fragilis': 'narrow',
  'Deparia acrostichoides': 'broad',
  'Dryopteris goldiana': 'narrow',
  'Dryopteris cristata': 'narrow',
  'Dryopteris clintoniana': 'narrow',
  'Pellaea atropurpurea': 'very-narrow',
  'Polypodium appalachianum': 'narrow',
  'Botrypus virginianus': 'triangle',
  'Sceptridium dissectum': 'triangle',
  'Athyrium angustum': 'narrow',
  'Asplenium scolopendrium': 'very-narrow',
  'Dryopteris filix-mas': 'narrow',
  'Ophioglossum vulgatum': 'very-narrow',
  'Ophioglossum azoricum': 'very-narrow',
  'Ophioglossum lusitanicum': 'very-narrow',
  'Asplenium ceterach': 'narrow',
  'Polystichum lonchitis': 'narrow',
  'Asplenium viride': 'very-narrow',
  'Asplenium marinum': 'narrow',
  'Botrychium lunaria': 'narrow',
  'Struthiopteris spicant': 'narrow',
  'Polypodium cambricum': 'narrow',
  'Polypodium interjectum': 'narrow',
  'Polypodium vulgare': 'narrow',
  'Vandenboschia speciosa': 'narrow',
  'Hymenophyllum tunbridgense': 'narrow',
  'Hymenophyllum wilsonii': 'narrow',
  'Asplenium septentrionale': 'narrow',
  'Asplenium ruta-muraria': 'narrow',
  'Adiantum capillus-veneris': 'multi-triangle',
  'Anogramma leptophylla': 'very-narrow',
  'Woodsia alpina': 'narrow',
  'Woodsia ilvensis': 'narrow',
  'Asplenium obovatum subsp. lanceolatum': 'narrow',
  'Asplenium adiantum-nigrum': 'triangle',
  'Dryopteris submontana': 'narrow',
  'Dryopteris oreades': 'narrow',
  'Dryopteris affinis': 'narrow',
  'Dryopteris borreri': 'narrow',
  'Dryopteris cambrensis': 'narrow',
  'Athyrium distentifolium': 'narrow',
  'Athyrium distentifolium var. flexile': 'narrow',
  'Oreopteris limbosperma': 'narrow',
  'Polystichum setiferum': 'narrow',
  'Polystichum aculeatum': 'narrow',
  'Cystopteris diaphana': 'narrow',
  'Cystopteris dickieana': 'narrow',
  'Pteridium pinetorum': 'triangle',
  'Gymnocarpium robertianum': 'triangle',
  'Cryptogramma crispa': 'narrow',
  'Cystopteris montana': 'narrow',
  'Asplenium onopteris': 'narrow',
  'Dryopteris aemula': 'narrow',
  'Dryopteris expansa': 'triangle',
  'Dryopteris dilatata': 'triangle',
  'Cyathea smithii': 'triangle',
  'Trichomanes reniforme': 'very-narrow',
  'Dicksonia antarctica': 'triangle',
  'Cyathea australis': 'triangle',
  'Cyathea cooperi': 'triangle',
  'Cyathea leichhardtiana': 'triangle',
  'Dicksonia youngiae': 'triangle',
  'Polystichum polyblepharum': 'narrow',
  'Athyrium niponicum': 'narrow',
  'Cyrtomium falcatum': 'very-narrow',
  'Cyrtomium fortunei': 'very-narrow',
  'Woodwardia japonica': 'narrow',
  'Dryopteris erythrosora': 'triangle',
  'Dryopteris crassirhizoma': 'triangle',
  'Osmunda japonica': 'triangle',
  'Deparia petersenii': 'narrow',
  'Matteuccia orientalis': 'narrow',
  'Lygodium japonicum': 'multi-triangle',
  'Plagiogyria japonica': 'narrow',
};
